### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by vivekpanjwani**
Updation for Email and Phone

### CODE REVIEW

**Comment by rahul-rb-frontend** [comment]
image

After putting the new html, CSS and JavaScript provided, it's looking like this. Is there a way to fix it? It this gets fixed then make a new PR and then I can merge it.

**Comment by vivekpanjwani** [comment]
Okk

**Comment by vivekpanjwani** [comment]
[
Screenshot 2023-10-20 173428
](url)

**Comment by vivekpanjwani** [comment]
Hello Now can you merge with label hacktober-accepted 
please

**Pull request closed without merging**
